server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/case_school?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # model的包
  type-aliases-package: com.xg.school.vo
  configuration:
    map-underscore-to-camel-case: true

